### ISSUE TITLE
[Bug]: register_buffer should be used rather than registering a no_grad parameter

### ISSUE THREAD

**Issue by typoverflow** [typoverflow/UtilsRL#11]
### Prerequisites

- [X] I have tried updating UtilsRL but nothing works.
- [X] I have checked both open and closed issues but found nothing that helps.

### UtilsRL version

0.4.4

### System info

Ubuntu 20.04

### What I am expecting

When creating a tensor which needs save&loading but not training inside a module, it is recommended to use `register_buffer` rather than creating `Parameter(..., requires_grad=False)`. The former method avoids returning the tensor when calling `Module.parameters()`. 

### What actually happened

None.

### Any additional messages which might help

Related to [this issue](https://github.com/x35f/unstable_baselines/pull/39).

### Urgency

Not a big problem.

**Comment by StepNeverStop** [comment]
In some cases, we want to calculate gradients by ourselves so as to better deal with post-calculation processing.
`nn.Parameter` with `requires_grad=False` will cause `RuntimeError: One of the differentiated Tensors does not require grad`.
There is a simple example:
```python
import torch as t
import torch.nn.functional as F
from torch import nn


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self._x = nn.Parameter(t.Tensor(2, 2))
        self._y = nn.Parameter(t.Tensor(2, 2), requires_grad=False)

    def forward(self, input):
        return input @ self._x @ self._y

    def calculate_gradient_manually(self, out):
        tge = t.randn((1, 2))
        loss = F.mse_loss(out, tge)
        grads = t.autograd.grad(loss, self.parameters(), retain_graph=True)
        return grads


if __name__ == "__main__":
    inp = t.randn((1, 2))
    net = Net()
    out = net(inp)
    print(net.calculate_gradient_manually(out=out))
```

By running the above code, we will get the wrong message: `RuntimeError: One of the differentiated Tensors does not require grad`. But if we change the way to register parameters within a `nn.Module` class just like the official code doing, we could fix/avoid (in future complex programs maybe) this problem:

```python
import torch as t
import torch.nn.functional as F
from torch import nn


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self._x = nn.Parameter(t.Tensor(2, 2))
        self.register_buffer("_y", t.Tensor(2, 2))

    def forward(self, input):
        return input @ self._x @ self._y

    def calculate_gradient_manually(self, out):
        tge = t.randn((1, 2))
        loss = F.mse_loss(out, tge)
        grads = t.autograd.grad(loss, self.parameters(), retain_graph=True)
        return grads


if __name__ == "__main__":
    inp = t.randn((1, 2))
    net = Net()
    out = net(inp)
    print(net.calculate_gradient_manually(out=out))
```

Also, parameters registered by using this kind of method whether requiring gradients or not could be saved/loaded through `.state_dict()`/`.load_state_dict()`.

**Comment by typoverflow** [comment]
Hello, 
I agree that `register_buffer` should be a preferable way to create a no_grad tensor. From PyTorch docs, it is deemed as a convention that the module's parameters all require gradient. 
Thanks for providing the snippets and the explanation. There is an upcoming patch (#12) to fix this problem : )

**Comment by typoverflow** [comment]
PR #12 fixed this. Closing this issue.
